### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozwebqa-dashboard#55]
I noticed we have a 'dumps' directory, along with some other files that have not been touched for many years. Can we go through and clean these up?

**Comment by edmorley** [comment]
As part of bug 1003236, I've been searching for legacy BzAPI usages - and came across the URL entries in some of the files in `dumps/`. These do appear unused - removing them would help avoid similar confusion / time spent checking if they are active.

Thanks :-)

**Comment by davehunt** [comment]
I suspect the following can be removed:
- [x] dumps
- [ ] img
- [ ] js/vendor
- [ ] fabfile.py
- [ ] requirements.txt
- [ ] setup.py
- [ ] testparser.py
- [ ] update.sh

**Comment by davehunt** [comment]
@stephendonner do you want to take this?

**Comment by stephendonner** [comment]
@davehunt yep!

**Comment by davehunt** [comment]
This has been done.
