### ISSUE TITLE
add/remove filter labels directly from dashboard

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/mozwebqa-dashboard#57]
The dashboard currently allows you to toggle which labels to show and hide, but labels are inconsistently applied throughout various projects. One solution is to manual clean up the labels, but a better method might be to make the dashboard the authority on which labels are applied (done via dashboard triages). 

An issue visible in the dashboard should have the option to check off the available labels, which would update the github issue/pull via the github api.

**Comment by davehunt** [comment]
We talked about using the GitHub API to apply a consistent core set of labels across our repositories. This enhancement would be a convenience for adding/removing these core labels on pull requests and issues directly from the dashboard.
