### ISSUE TITLE
Add link to github repos next to project titles

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/mozwebqa-dashboard#58]
In the project list you can expand/collapse a project to view it's issues/pulls, but there is no easy way to get to the project repo on github - you can get to a specific issue and then go back to the main project, but would be nice to link directly to the project

**Comment by davehunt** [comment]
Perhaps we could use a little :octocat: icon?

**Comment by ghost** [comment]
@davehunt Can I pick up this issue?

**Comment by davehunt** [comment]
@AkshayGulhane of course! I've invited you to be a collaborator for this repository. Once you accept I can assign the issue to you. In the meantime, please feel free to get started.

**Comment by ghost** [comment]
@davehunt Thanks Dave! I have started working on it. 
However, I can not find the projects list on the dashboard.
Can you let me know how to navigate to that page?

**Comment by davehunt** [comment]
@AkshayGulhane thanks for letting us know - I've fixed the issue and the project should be listed on the issues and pull requests pages.

**Comment by davehunt** [comment]
Fixed in #74
