### ISSUE TITLE
Replace references to MozWebQA with MozQA

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/mozwebqa-dashboard#59]
Illustrates that the dashboard could be for any QA triage and overview, for projects outside of WebQA scope

**Comment by davehunt** [comment]
I think we should actually make the name configurable. At the moment the projects are all web QA related, and the project is called mozwebqa-dashboard. I think there's value in making it a generic GitHub dashboard that can be tweaked through configuration.

**Comment by justinpotts** [comment]
@stuartphilp @davehunt What would you like to be called for the Heroku domain? If we make it configurable we can keep it as MozWebQA for the actual hosted dashboard itself, but I'm open to suggestions on what you guys would like to do.

**Comment by davehunt** [comment]
I'd suggest coming up with a new name for the dashboard project. The deployed dashboard with configuration to match can remain mozwebqa for now, and perhaps we can work on a combined mozqa instance in August. Once that's up and running we can redirect from the mozwebqa one.

**Comment by stephendonner** [comment]
https://github.com/mozilla/mozwebqa-dashboard/pull/66 took care of most of this, didn't it?  The rename itself, at least.

**Comment by davehunt** [comment]
Closed based on @stephendonner's comment.
