### ISSUE TITLE
User Avatars enlarged on screens < 992px

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/mozwebqa-dashboard#75]
Relative sizing (`width="60%" height="60%"`) is causing user avatars to display very large on screens smaller than 992px

sorry @m8ttyB :stuck_out_tongue: 

<img src="https://cloud.githubusercontent.com/assets/18633586/20272195/70a28e68-aa4a-11e6-90a6-65dd8910f095.png" width="250"/>

**Comment by kimberlythegeek** [comment]
Edit: Not caused by relative sizing alone, but also lack of responsive bootstrap classes

The container for user avatars: `<div class="col-md-1">`
and the container for Issue text/description `<div class="col-md-11">`

adding Bootstrap grid classes for `sm` and `xs` screens, as well as setting `width: 60px` will resolve issue

**Comment by davehunt** [comment]
Thanks for opening the issue @kimberlythegeek.. are you interested in submitting a patch? This addresses part of #38.

**Comment by kimberlythegeek** [comment]
@davehunt I am. And just did :smile:

**Comment by davehunt** [comment]
fixed by #75
