### ISSUE TITLE
Add links to readthedocs and servicebook

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/mozwebqa-dashboard#79]

**Comment by kimberlythegeek** [comment]
attach the links and I'll get them added 😄

**Comment by davehunt** [comment]
readthedocs: http://firefox-test-engineering.readthedocs.io/

**Comment by davehunt** [comment]
No idea about Service Book. @tarekziade?

**Comment by stephendonner** [comment]
http://servicebook.dev.mozaws.net/
