### ISSUE TITLE
Make It Pretty!

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/mozwebqa-dashboard#81]
<a href="https://cloud.githubusercontent.com/assets/18633586/21060793/84ec9538-be06-11e6-83d8-a1c00e2797aa.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21060793/84ec9538-be06-11e6-83d8-a1c00e2797aa.png" height="100" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21060796/84f23808-be06-11e6-8512-0bd9d15754b0.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21060796/84f23808-be06-11e6-8512-0bd9d15754b0.png" height="100" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21060794/84ef24ce-be06-11e6-8e4e-f7d8d3366054.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21060794/84ef24ce-be06-11e6-8e4e-f7d8d3366054.png" width="100" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21060797/84f3a3be-be06-11e6-8f31-b5d64863294d.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21060797/84f3a3be-be06-11e6-8f31-b5d64863294d.png" width="100" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21060798/84f5048e-be06-11e6-93ba-ba1793cc7f5e.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21060798/84f5048e-be06-11e6-93ba-ba1793cc7f5e.png" height="100" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21060795/84f1d890-be06-11e6-916f-74f9717883a9.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21060795/84f1d890-be06-11e6-916f-74f9717883a9.png" height="100" /></a>

**Comment by kimberlythegeek** [comment]
Make design more aesthetic, as well as consistent. Make navmenu functional. Add "toggle all" to repo list.

I welcome feedback!
If the labels aren't easily readable for you, let me know.

FYI: I don't consider these design final, still more tweaking to do

**Comment by stephendonner** [comment]
I think it looks fantastic; one small (bug) I noticed is "[TestEngineering]:Wiki" appears to be raw markup?

Other than that, so far I think it looks great; thanks!

**Comment by kimberlythegeek** [comment]
Actually that was intentional. I wasn't sure how to format it, wiki was too short, Firefox test engineering wiki was too long (imo). 

 I was following the format that I've seen on some other sites. If you think it looks weird I can change it to just test engineering wiki :smile:

**Comment by davehunt** [comment]
The last redesign was only [6 months ago](https://github.com/mozilla/fxtest-dashboard/pull/35), and was drawing from the [Mozilla styleguide](https://www.mozilla.org/en-US/styleguide/websites/sandstone/). While I do like this design, it is a departure from sandstone.

**Comment by kimberlythegeek** [comment]
Thanks for the feedback @davehunt 

Hadn't seen that before now. I was modeling it on a Mozilla bootstrap theme I found [mozilla/mofo-boostrap](http://github.com/mozilla/mofo-boostrap)

I didn't feel the design was very consistent or aesthetic, which was my reason for starting the redesign, but I do like the Sandstone look. I can make something like that :smile:

I was considering adding the Mozilla logo before seeing that, if I did, would you prefer the traditional logo or the developer logo? 

Thanks again 👍

**Comment by davehunt** [comment]
Thanks Kimberly, I appreciate you've clearly spent time on this. If you can find a way to evolve the design with sandstone in mind, that would be awesome!

I love the filters in the sidebar. I know that's something we struggled with before. For the logo, I'd vote for the traditional one.

Cheers,
Dave

**Comment by kimberlythegeek** [comment]
<a href="https://cloud.githubusercontent.com/assets/18633586/21108855/d8cff22c-c053-11e6-826e-aeb5a30df2a3.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21108855/d8cff22c-c053-11e6-826e-aeb5a30df2a3.png" height="200" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21108854/d8cea9bc-c053-11e6-962b-43dd3f0756f2.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21108854/d8cea9bc-c053-11e6-962b-43dd3f0756f2.png" height="200" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21108858/d8d23d70-c053-11e6-98de-1d14f53b1269.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21108858/d8d23d70-c053-11e6-98de-1d14f53b1269.png" height="200" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21108856/d8d0cfd0-c053-11e6-9e40-5a25a890b7a3.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21108856/d8d0cfd0-c053-11e6-9e40-5a25a890b7a3.png" height="200" /></a>
<a href="https://cloud.githubusercontent.com/assets/18633586/21108857/d8d13ac4-c053-11e6-9a37-5b187d4c88dd.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21108857/d8d13ac4-c053-11e6-9a37-5b187d4c88dd.png" height="200" /></a>

**Comment by kimberlythegeek** [comment]
So they have different color schemes for the Sandstone style guide, I went with the one used for (now-deprecated) [mozillalabs.com](http://www.mozillalabs.com)

**Comment by kimberlythegeek** [comment]
The nav links are in the header right now, but it wouldn't be too much trouble to move them into the fixed sidebar. Didn't think about that until just now!

**Comment by kimberlythegeek** [comment]
<a href="https://cloud.githubusercontent.com/assets/18633586/21146577/720a5066-c10f-11e6-8830-e77b8dd7d106.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21146577/720a5066-c10f-11e6-8830-e77b8dd7d106.png" height="200"/></a>  <a href="https://cloud.githubusercontent.com/assets/18633586/21146578/720e6390-c10f-11e6-8e39-e0487c27a2b5.png"><img src="https://cloud.githubusercontent.com/assets/18633586/21146578/720e6390-c10f-11e6-8e39-e0487c27a2b5.png" height="200" /></a>

**Comment by davehunt** [comment]
Looks good, thanks @kimberlythegeek
